# Site settings
title: "CV - Lewis W. Miller"
description: "My CV, a delicious free sample"

# Run a server: `cd "D:\HDD Documents\Websites\Resume\resume-template"` `bundle exec jekyll serve --port 4000`

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Lewis W. Miller"
resume_title:                   "Computer Science Student at Bournemouth School"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "lmiller81694@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+447798887549"
#resume_contact_address:         ""

resume_header_contact_info:     "• lmiller81694@gmail.com •"
display_header_contact_info:    "true"

resume_header_intro: >
    <p>I am an A-Level student studying at Bournemouth School for Boys. Currently capable of working with
    <ul>
      <li>C# (.NET Core and Framework)</li>
      <li>Node.JS</li>
      <li>Python</li>
    </ul>
    And am always willing to learn new languages and frameworks.
    </p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
#resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/nightmarlin"
  #resume_twitter_url:           "#"
  #resume_dribbble_url:          "#"
  #resume_facebook_url:          "#"
  #resume_linkedin_url:          "#"
  #resume_instagram_url:         "https://www.instagram.com/blue.nightmarlin"
  resume_website_url:           "http://www.lwmiller.co.uk"
  #resume_medium_url:            "#"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
